### ISSUE TITLE
Failure due to exceeding vmem limit

### ISSUE THREAD

**Issue by bacaron** [dipy/bl_apps_dipy_fit_dki#2]
Hello,

I'm running into failures with some of my data using this app due to more vmem being needed than what's being requested. Would it be possible to increase the vmem? Maybe to 24GB?

Thank you,
Brad Caron

**Comment by skoudoro** [comment]
Hi @bacaron,

increase to 24Gb just done, Can you try again?

**Comment by bacaron** [comment]
Thanks @skoudoro!
